apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "req-counter.labels" . | nindent 4 }}
spec:
  type: Opaque
data:
  username: YW5qYW5zaW5oYTIwMDI= 
  password: QW5qYW5AMjAwMg==
  